export const HOME = "/"
export const CURSOS = "/cursos"
export const mostrarEstudiantes = "/estudiantes"
export const mostrarEstudiante = "/estudiantes/:id"
export const crearEstudiante = "/estudiantes/"
export const actualizarEstudiante = "/estudiantes/:id"
export const eliminarEstudiante = "/estudiantes/:id"