export const HOME = "/"
export const CURSOS = "/cursos"
export const VER_CURSO = "/cursos/:id"
export const CREAR_CURSO = "/cursos/crear"
export const EDITAR_CURSO = "/cursos/editar/:id"

export const mostrarEstudiantes = "/estudiantes"
export const mostrarEstudiante = "/estudiantes/:id"
export const crearEstudiante = "/estudiantes/"
export const actualizarEstudiante = "/estudiantes/:id"
export const eliminarEstudiante = "/estudiantes/:id"

export const INSCRIPCIONES = "/inscripciones"
export const CREAR_INSCRIPCIONES = "/inscripciones/crear"
export const EDITAR_INSCRIPCION = "/inscripcion/editar/:id"
